config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :keyword_mappings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/kamigo/eat', to: 'kamigo#eat'
  get '/kamigo/request_headers', to: 'kamigo#request_headers'
  get '/kamigo/request_body', to: 'kamigo#request_body'
  get '/kamigo/response_headers', to: 'kamigo#response_headers'
  get '/kamigo/response_body', to: 'kamigo#show_response_body'
  get '/kamigo/sent_request', to: 'kamigo#sent_request'
  post 'kamigo/webhook', to: 'kamigo#webhook'
  resources :push_messages, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
end

app/models/keyword_mapping.rb
class KeywordMapping < ApplicationRecord
end

app/models/received.rb
class Received < ApplicationRecord
end

app/models/reply.rb
class Reply < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
require 'net/http'
class ApplicationController < ActionController::Base
end

app/controllers/kamigo_controller.rb
require 'line/bot'
class KamigoController < ApplicationController
  protect_from_forgery with: :null_session

  def eat
    render plain: "卡米"
  end

  def request_headers
    render plain: request.headers.to_h.reject{|key, value| key.include?('.')}.map{|key, value| "#{key}:#{value}"}.sort.join("\n")
  end

  def request_body
    render plain: request.body
  end

  def response_headers
    response.headers["9527"] = "Y_Y"
    render plain: response.headers.map{ |key, value|
      "#{key}: #{value}"
    }.sort.join("\n")
  end

  def show_response_body
    puts "我在這 \\(￣▽￣)/"
    puts "===這是設定前的response.body:#{response.body}==="
    render plain: "哈哈哈"
    puts "===這是設定後的response.body:#{response.body}==="
  end

  def sent_request
    uri = URI('http://localhost:3000/kamigo/eat')
    http = Net::HTTP.new(uri.host, uri.port)
    http_request = Net::HTTP::Get.new(uri)
    http_response = http.request(http_request)

    render plain: JSON.pretty_generate({
      request_class: request.class,
      response_class: response.class,
      http_request_class: http_request.class,
      http_response_class: http_response.class
    })
  end

  def translate_to_korean(message)
    "#{message}u~"
  end

  def webhook
    # 記錄頻道(find_or_create_by避免相同的資料重複被存導致同一個人收到多次)
    Channel.find_or_create_by(channel_id: channel_id)

    # 學說話
    reply_text = learn(channel_id, received_text)

    # 設定回覆文字
    reply_text = keyword_reply(channel_id, received_text) if reply_text.nil?

    # 重複
    reply_text = echo2(channel_id, received_text) if reply_text.nil?

    # 紀錄
    save_to_received(channel_id, received_text)
    save_to_reply(channel_id, reply_text)

    # 傳送訊息到 line
    response = reply_to_line(reply_text)

    # 回應 200
    head :ok
    
  end

  def learn(channel_id, received_text)
    #如果開頭不是 卡米狗學說話; 就跳出
    return nil unless received_text[0..6] == '卡米狗學說話;'

    received_text = received_text[7..-1]
    semicolon_index = received_text.index(';')

    # 找不到分號就跳出
    return nil if semicolon_index.nil?

    keyword = received_text[0..semicolon_index-1]
    message = received_text[semicolon_index+1..-1]
    KeywordMapping.create(channel_id: channel_id, keyword: keyword, message: message)
    'got it ~'
  end
  
  # Line Bot API 物件初始化
  def line
    # return @line unless @line.nil?  
    @line ||= Line::Bot::Client.new{|config|
      config.channel_secret = '57d1d732a9dd3f02aeee87b3c882a481'
      config.channel_token = 'CvaRq33hjRaTSFurt8t24NPakKRZ7oVLs04nhOTeZydD3CCMpZtTAHcKPEgBoAtnHwt5QuO6i8oxKh6xXwvli+RqOGILUd4qY2AcOLgzbyPb5H7HZdrjn6pAQdYlFcaozRMWUtX9yFoDTXLM6CgEfAdB04t89/1O/w1cDnyilFU='
    }
  end

  # 傳送訊息到 line
  def reply_to_line(reply_text)
    return nil if reply_text.nil?

    # 取得reply token
    reply_token = params['events'][0]['replyToken']

    # 設定回覆訊息
    message = {
      type: 'text',
      text: reply_text
    }

    # 傳送訊息
    line.reply_message(reply_token, message)

  end

  # 取得對方說的話
  def received_text
    message = params['events'][0]['message']
    message['text'] unless message.nil?
  end

  def keyword_reply(channel_id, received_text)
    # 學習紀錄表
    message = KeywordMapping.where(channel_id: channel_id, keyword: received_text).last&.message
    return message unless message.nil?
    KeywordMapping.where(keyword: received_text).last&.message
    
  end

  def channel_id
    source = params['events'][0]['source']
    source['groupId'] || source['roomId'] || source['userId']
  end

  def save_to_received(channel_id, received_text)
    return if received_text.nil?
    Received.create(channel_id: channel_id, text: received_text)  
  end

  def save_to_reply(channel_id, reply_text)
    return if reply_text.nil?
    Reply.create(channel_id: channel_id, text: reply_text)
  end

  def echo2(channel_id, received_text)
    recent_received_texts = Received.where(channel_id: channel_id).last(5)&.pluck(:text)
    return nil unless received_text.in? recent_received_texts
    last_reply_text = Reply.where(channel_id: channel_id).last&.text
    return nil if last_reply_text == received_text
    received_text
  end

end

app/controllers/keyword_mappings_controller.rb
class KeywordMappingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_keyword_mapping, only: [:show, :edit, :update, :destroy]

  # GET /keyword_mappings
  # GET /keyword_mappings.json
  def index
    @keyword_mappings = KeywordMapping.all
  end

  # GET /keyword_mappings/1
  # GET /keyword_mappings/1.json
  def show
  end

  # GET /keyword_mappings/new
  def new
    @keyword_mapping = KeywordMapping.new
  end

  # GET /keyword_mappings/1/edit
  def edit
  end

  # POST /keyword_mappings
  # POST /keyword_mappings.json
  def create
    @keyword_mapping = KeywordMapping.new(keyword_mapping_params)

    respond_to do |format|
      if @keyword_mapping.save
        format.html { redirect_to @keyword_mapping, notice: 'Keyword mapping was successfully created.' }
        format.json { render :show, status: :created, location: @keyword_mapping }
      else
        format.html { render :new }
        format.json { render json: @keyword_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keyword_mappings/1
  # PATCH/PUT /keyword_mappings/1.json
  def update
    respond_to do |format|
      if @keyword_mapping.update(keyword_mapping_params)
        format.html { redirect_to @keyword_mapping, notice: 'Keyword mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword_mapping }
      else
        format.html { render :edit }
        format.json { render json: @keyword_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keyword_mappings/1
  # DELETE /keyword_mappings/1.json
  def destroy
    @keyword_mapping.destroy
    respond_to do |format|
      format.html { redirect_to keyword_mappings_url, notice: 'Keyword mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword_mapping
      @keyword_mapping = KeywordMapping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_mapping_params
      params.require(:keyword_mapping).permit(:channel_id, :keyword, :message)
    end
end

app/controllers/push_messages_controller.rb
require 'line/bot'
class PushMessagesController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    text = params[:text]
    Channel.all.each do |channel|
      push_to_line(channel.channel_id, text)
    end
    redirect_to '/push_messages/new'
  end

  def push_to_line(channel_id, text)
    return nil if channel_id.nil? or text.nil?
    
    # 設定回覆訊息
    message = {
      type: 'text',
      text: text
    } 

    # 傳送訊息
    line.push_message(channel_id, message)
  end

  def line
    @line ||= Line::Bot::Client.new { |config|
      config.channel_secret = '57d1d732a9dd3f02aeee87b3c882a481'
      config.channel_token = 'CvaRq33hjRaTSFurt8t24NPakKRZ7oVLs04nhOTeZydD3CCMpZtTAHcKPEgBoAtnHwt5QuO6i8oxKh6xXwvli+RqOGILUd4qY2AcOLgzbyPb5H7HZdrjn6pAQdYlFcaozRMWUtX9yFoDTXLM6CgEfAdB04t89/1O/w1cDnyilFU='
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keyword_mappings_helper.rb
module KeywordMappingsHelper
end

app/views/kamigo/eat.html.erb
<h1>卡米卡米</h1>

app/views/keyword_mappings/_form.html.erb
<%= form_with(model: keyword_mapping, local: true) do |form| %>
  <% if keyword_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(keyword_mapping.errors.count, "error") %> prohibited this keyword_mapping from being saved:</h2>

      <ul>
      <% keyword_mapping.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.text_field :channel_id %>
  </div>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_field :keyword %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/keyword_mappings/edit.html.erb
<h1>Editing Keyword Mapping</h1>

<%= render 'form', keyword_mapping: @keyword_mapping %>

<%= link_to 'Show', @keyword_mapping %> |
<%= link_to 'Back', keyword_mappings_path %>

app/views/keyword_mappings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keyword Mappings</h1>

<table>
  <thead>
    <tr>
      <th>Channel</th>
      <th>Keyword</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keyword_mappings.each do |keyword_mapping| %>
      <tr>
        <td><%= keyword_mapping.channel_id %></td>
        <td><%= keyword_mapping.keyword %></td>
        <td><%= keyword_mapping.message %></td>
        <td><%= link_to 'Show', keyword_mapping %></td>
        <td><%= link_to 'Edit', edit_keyword_mapping_path(keyword_mapping) %></td>
        <td><%= link_to 'Destroy', keyword_mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword Mapping', new_keyword_mapping_path %>

app/views/keyword_mappings/new.html.erb
<h1>New Keyword Mapping</h1>

<%= render 'form', keyword_mapping: @keyword_mapping %>

<%= link_to 'Back', keyword_mappings_path %>

app/views/keyword_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @keyword_mapping.channel_id %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @keyword_mapping.keyword %>
</p>

<p>
  <strong>Message:</strong>
  <%= @keyword_mapping.message %>
</p>

<%= link_to 'Edit', edit_keyword_mapping_path(@keyword_mapping) %> |
<%= link_to 'Back', keyword_mappings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kamigo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/push_messages/new.html.erb
<%= form_with(url: '/push_messages', local: true) do |form| %>
  <%= text_area_tag 'text' %>
  <%= submit_tag "送出" %>
<% end %>